### ISSUE TITLE
Koa or Express

### ISSUE THREAD

**Issue by yankeeinlondon** [HelixOne/leto#3]
I noticed the demo leto page suggests the application serving is being done via Koa but on Github it suggests Express. Should make that consistent.

**Comment by zubair-io** [comment]
There is `server.ts`  that uses expressjs and there is `server-koa.ts`  That are both basic servers, but `server-koa.ts` does not support server side rendering. I will update the demos and add some documentation

**Comment by zubair-io** [comment]
45683e7
